import { fetchFromProvider } from '../core/fetch';
import { buildProvenance } from '../core/provenance';
import { fail, ok, type ConnectorResult, type DataSeries, type Observation } from '../core/types';

/**
 * OECD Data Explorer SDMX API - handoff pp. 219-220 (Provider ID: oecd-sdmx).
 *
 * p. 220: "Use the API query generated by Data Explorer rather than inventing
 * dimension positions." The two dataflow IDs and their versions below were
 * read from the live structure endpoint on 2026-09-19, not guessed:
 *
 *   GET /public/rest/dataflow/OECD.ENV.EPI?format=json-structure-2.0.0
 *   GET /public/rest/dataflow/OECD.DCD.FSD?format=json-structure-2.0.0
 *
 * Versions matter. `DSD_RIOMRKR@DF_RIOMARKERS` is at 1.6, and pinning the
 * wrong version returns NoResultsFound rather than an error you can read.
 */

/**
 * OECD serves different subject areas from different bases, and a dataflow
 * queried against the wrong one answers HTTP 500 rather than 404. Each
 * dataflow therefore carries its own. The base is discoverable from the `self`
 * link on the dataflow's own structure response.
 */
const PUBLIC_BASE = 'https://sdmx.oecd.org/public/rest/data';
const DCD_BASE = 'https://sdmx.oecd.org/dcd-public/rest/data';

export const OECD_DATAFLOWS = {
  municipalWaste: {
    base: PUBLIC_BASE,
    flow: 'OECD.ENV.EPI,DSD_MUNW@DF_MUNW,1.0',
    label: 'Municipal waste: generation and treatment',
    sourceUrl: 'https://data-explorer.oecd.org/vis?fs[0]=Topic%2C1%7CEnvironment%23ENV%23%7CWaste%23ENV_WAS%23',
    interpretation:
      'Municipal waste definitions and treatment coverage vary by country, so cross-country comparisons are indicative.',
  },
  /**
   * ⚠️ NOT YET USABLE FROM THE SERVER. The data route answers HTTP 403 with an
   * HTML body for every key tried on 2026-09-20, including the empty key.
   * p. 220 anticipates this: "Some large CRS query parameters are restricted"
   * and "VPN/anonymised-origin traffic not allowed".
   *
   * Everything else is confirmed, so whoever picks this up does not start from
   * nothing:
   *   base      https://sdmx.oecd.org/dcd-public/rest/data
   *   dataflow  OECD.DCD.FSD,DSD_RIOMRKR@DF_RIOMARKERS,1.6
   *   key       12 dimensions in this order -
   *             DONOR.RECIPIENT.SECTOR.MEASURE.ALLOCABLE.MARKER.SCORE.
   *             FLOW_TYPE.PRICE_BASE.MD_DIM.MD_ID.UNIT_MEASURE
   *   codelists CL_CRS_MARKER, CL_CRS_MEASURE, CL_CRS_SCORE, CL_FLOW_TYPE
   *
   * p. 220 says to take the query from the Data Explorer query builder rather
   * than invent dimension positions, so the last step is to generate a narrow
   * key there and paste it in - not to guess one here.
   */
  climateRelatedFinance: {
    base: DCD_BASE,
    flow: 'OECD.DCD.FSD,DSD_RIOMRKR@DF_RIOMARKERS,1.6',
    label: 'Climate-related development finance (Rio markers)',
    sourceUrl: 'https://data-explorer.oecd.org/vis?fs[0]=Topic%2C1%7CDevelopment%23DEV%23',
    // p. 220 is unusually specific about how this must be described.
    interpretation:
      'Climate-related development finance, not all global climate finance. Rio-marker amounts can include whole project values rather than climate-specific components. Commitments and disbursements are different things and are not interchangeable. Adaptation and mitigation totals overlap and must not be added together without deduplication.',
  },
} as const;

export type DataflowKey = keyof typeof OECD_DATAFLOWS;

/**
 * SDMX-JSON with `dimensionAtObservation=AllDimensions`.
 *
 * The gateway answers in either SDMX-JSON 1.0 or 2.0 depending on the request,
 * and the two differ in one awkward way: 1.0 puts a single `structure` object
 * on `data`, while 2.0 puts an array under `structures`. Both are handled,
 * because relying on one produced an empty chart rather than an error.
 */
type SdmxStructure = {
  dimensions?: { observation?: { id: string; values: { id: string; name?: string }[] }[] };
  attributes?: { observation?: { id: string; values: { id: string; name?: string }[] }[] };
};

type SdmxJson = {
  data?: {
    dataSets?: { observations?: Record<string, (number | null)[]> }[];
    /** SDMX-JSON 2.0 */
    structures?: SdmxStructure[];
    /** SDMX-JSON 1.0 */
    structure?: SdmxStructure;
  };
};

function dimensionName(value: { id: string; name?: string } | undefined): string {
  return value?.name ?? value?.id ?? '';
}

/**
 * Fetch one slice and fold it into series.
 *
 * `key` is the SDMX dimension key generated by Data Explorer, e.g.
 * "FRA+DEU...." - dots separate dimensions in order, a `+` joins alternatives,
 * and an empty position means "all".
 */
export async function fetchOecdSlice(options: {
  dataflow: DataflowKey;
  key: string;
  startPeriod: string;
  endPeriod: string;
  /** Keep only these MEASURE ids. Without it a flow can return dozens. */
  measures?: string[];
  maxSeries?: number;
}): Promise<ConnectorResult<DataSeries[]>> {
  const { dataflow, key, startPeriod, endPeriod, measures, maxSeries = 12 } = options;
  const flow = OECD_DATAFLOWS[dataflow];

  const params = new URLSearchParams({
    startPeriod,
    endPeriod,
    format: 'jsondata',
    dimensionAtObservation: 'AllDimensions',
  });

  const url = `${flow.base}/${flow.flow}/${key}?${params.toString()}`;
  const res = await fetchFromProvider<SdmxJson>('oecd-sdmx', url, {
    timeoutMs: 25000,
    // The OECD SDMX gateway answers HTTP 500 - not 406 - when it is sent
    // `Accept: application/json`, and 200 when it is sent `*/*`. Verified
    // 2026-09-20 on an otherwise identical request. The format is already
    // chosen by `format=jsondata` in the query string, so nothing is lost by
    // asking for anything. Do not "tidy" this back to application/json.
    headers: { Accept: '*/*' },
  });
  if (!res.ok) return res;

  const structure = res.data?.data?.structures?.[0] ?? res.data?.data?.structure;
  const dims = structure?.dimensions?.observation ?? [];
  const observations = res.data?.data?.dataSets?.[0]?.observations ?? {};

  if (dims.length === 0 || Object.keys(observations).length === 0) {
    return fail('oecd-sdmx', 'no_results', 'OECD returned no observations for this selection.');
  }

  const timeIndex = dims.findIndex((d) => d.id === 'TIME_PERIOD');
  const areaIndex = dims.findIndex((d) => d.id === 'REF_AREA');
  const measureIndex = dims.findIndex((d) => d.id === 'MEASURE');
  const unitIndex = dims.findIndex((d) => d.id === 'UNIT_MEASURE');

  // Group every observation by everything except the time dimension: that
  // grouping IS the series.
  const grouped = new Map<string, { dimIds: number[]; points: Observation[] }>();

  for (const [coord, values] of Object.entries(observations)) {
    const idx = coord.split(':').map((n) => Number.parseInt(n, 10));
    if (idx.some(Number.isNaN)) continue;

    if (measures && measureIndex >= 0) {
      const measureId = dims[measureIndex]?.values[idx[measureIndex]]?.id;
      if (measureId && !measures.includes(measureId)) continue;
    }

    const seriesKey = idx.map((v, i) => (i === timeIndex ? '*' : v)).join(':');
    const period = timeIndex >= 0 ? dimensionName(dims[timeIndex].values[idx[timeIndex]]) : '';
    const raw = values?.[0];

    const bucket = grouped.get(seriesKey) ?? { dimIds: idx, points: [] };
    bucket.points.push({ period, value: typeof raw === 'number' ? raw : null });
    grouped.set(seriesKey, bucket);
  }

  const series: DataSeries[] = [...grouped.entries()]
    .slice(0, maxSeries)
    .map(([seriesKey, bucket]) => {
      const area = areaIndex >= 0 ? dimensionName(dims[areaIndex].values[bucket.dimIds[areaIndex]]) : null;
      const measure = measureIndex >= 0 ? dimensionName(dims[measureIndex].values[bucket.dimIds[measureIndex]]) : flow.label;
      const unit = unitIndex >= 0 ? dimensionName(dims[unitIndex].values[bucket.dimIds[unitIndex]]) : 'Not stated';
      const points = bucket.points.sort((a, b) => a.period.localeCompare(b.period));

      return {
        id: `oecd-${dataflow}-${seriesKey}`,
        label: area ? `${area} — ${measure}` : measure,
        unit,
        frequency: 'annual' as const,
        measureNote: flow.interpretation,
        area,
        observations: points,
        provenance: buildProvenance('oecd-sdmx', {
          sourceUrl: flow.sourceUrl,
          sourceId: `${flow.flow}/${key}`,
          observationPeriod: points.length ? `${points[0].period}–${points[points.length - 1].period}` : null,
          version: flow.flow.split(',')[2] ?? null,
          accessStatus: 'verified_open',
          accessEvidence: 'OECD Data Explorer and the public SDMX API are open without a key; checked 2026-09-19.',
          transformations: [
            'Grouped SDMX observations into series by every dimension except TIME_PERIOD',
            'Sorted observations by period',
          ],
        }),
      };
    });

  if (series.length === 0) {
    return fail('oecd-sdmx', 'no_results', 'No matching OECD series after filtering.');
  }
  return ok('oecd-sdmx', series);
}
