/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    publications: Publication;
    tools: Tool;
    team: Team;
    categories: Category;
    authors: Author;
    domains: Domain;
    industries: Industry;
    datasets: Dataset;
    dashboards: Dashboard;
    'external-items': ExternalItem;
    glossary: Glossary;
    faqs: Faq;
    enquiries: Enquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    tools: ToolsSelect<false> | ToolsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    domains: DomainsSelect<false> | DomainsSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    datasets: DatasetsSelect<false> | DatasetsSelect<true>;
    dashboards: DashboardsSelect<false> | DashboardsSelect<true>;
    'external-items': ExternalItemsSelect<false> | ExternalItemsSelect<true>;
    glossary: GlossarySelect<false> | GlossarySelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar') | ('en' | 'ar')[];
  globals: {
    'knowledge-hub-config': KnowledgeHubConfig;
    'data-portal-sources-config': DataPortalSourcesConfig;
  };
  globalsSelect: {
    'knowledge-hub-config': KnowledgeHubConfigSelect<false> | KnowledgeHubConfigSelect<true>;
    'data-portal-sources-config': DataPortalSourcesConfigSelect<false> | DataPortalSourcesConfigSelect<true>;
  };
  locale: 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  /**
   * URL slug for the dedicated page
   */
  slug: string;
  heading: string;
  excerpt: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * SEO Title
   */
  metaTitle?: string | null;
  /**
   * SEO Description
   */
  metaDescription?: string | null;
  /**
   * SEO Keywords
   */
  metaKeywords?: string | null;
  /**
   * SEO Open Graph Image
   */
  ogImage?: (number | null) | Media;
  /**
   * Case Study was removed: handoff p. 229 requires that no Case Study surface appears anywhere.
   */
  type: 'White Paper' | 'Article' | 'Research' | 'Conference Paper';
  /**
   * Approved byline, exactly as it should be published.
   */
  author?: string | null;
  /**
   * Drives the K03 Language filter. Do not label a publication Arabic until a real translation exists (p. 227).
   */
  language?: ('en' | 'ar') | null;
  /**
   * Optional secondary tag carried over from the 2024 archive.
   */
  archiveCategory?:
    | (
        | 'climate-science-and-impacts'
        | 'energy-technology-and-finance'
        | 'environment-and-society'
        | 'frameworks-and-methodologies'
      )
    | null;
  /**
   * Only Article records appear in the public Enerqa Publication collection.
   */
  recordKind: 'article' | 'category-heading' | 'biography';
  /**
   * Tick once this publication's real publication date has been confirmed against the original source.
   */
  dateVerified?: boolean | null;
  topic?: (number | Category)[] | null;
  date: string;
  file?: (number | null) | Media;
  bgGradientType: 'Green' | 'Red' | 'Blue' | 'Dark';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools".
 */
export interface Tool {
  id: number;
  slug: string;
  category: string;
  type: 'interactive' | 'informational';
  title: string;
  desc: string;
  image?: (number | null) | Media;
  /**
   * External link or native route (e.g. /tools/carbon-calculator)
   */
  link?: string | null;
  /**
   * URL to embed if this is an external interactive tool (e.g. Tableau dashboard)
   */
  iframeUrl?: string | null;
  /**
   * PDF or document download for informational guides
   */
  file?: (number | null) | Media;
  industries?: (number | Industry)[] | null;
  version?: string | null;
  access?: ('Request Access' | 'Public' | 'Enterprise') | null;
  purpose?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  inputs?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  outputs?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  method?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  privacy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  title: string;
  slug: string;
  /**
   * Optional. Background image for the industry hero banner. Falls back to brand gradient if empty.
   */
  heroImage?: (number | null) | Media;
  heroNarrative: string;
  /**
   * Text for the call to action button (e.g. Discuss Your Project)
   */
  ctaText?: string | null;
  /**
   * Short industry-specific lifecycle narrative (module I01L).
   */
  lifecycleNarrative?: string | null;
  /**
   * Relevant Domains and Work Areas (3-4 contextual links to domain capability anchors)
   */
  workAreas?:
    | {
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tools mapped to this industry in the handoff. Use approved availability labels - do not assume a tool is publicly launched.
   */
  relevantTools?:
    | {
        label: string;
        /**
         * Internal path, e.g. /tools/esg-readiness
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Provider IDs recommended for this industry, with the handoff note on what each covers and its limits.
   */
  dataSources?:
    | {
        provider: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * SEO Title
   */
  metaTitle?: string | null;
  /**
   * SEO Description
   */
  metaDescription?: string | null;
  /**
   * SEO Keywords
   */
  metaKeywords?: string | null;
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  bio: string;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains".
 */
export interface Domain {
  id: number;
  title: string;
  slug: string;
  /**
   * Optional. Background image for the domain hero banner. Falls back to brand gradient if empty.
   */
  heroImage?: (number | null) | Media;
  heroNarrative: string;
  ctaText?: string | null;
  capabilities?:
    | {
        heading: string;
        /**
         * Stable, heading-derived anchor (handoff p. 227). Becomes the #anchor on the domain page - changing it breaks existing links.
         */
        slug: string;
        narrative: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Industries where this domain applies. Selected through the shared domain/industry taxonomy (handoff p. 28). Leave empty until the mapping is agreed.
   */
  relevantIndustries?: (number | Industry)[] | null;
  policyUpdates?: {
    /**
     * Exact website heading for this domain, e.g. "Policy and Official Updates" (climate) or "Corporate Disclosures and Finance Updates" (ESG). Handoff pp. 29, 37, 48, 59.
     */
    heading?: string | null;
    narrative?: string | null;
    /**
     * Editor-facing note on which verified open-access providers feed this module. Shown to visitors as the source line.
     */
    sourceNote?: string | null;
  };
  relevantTools?:
    | {
        label: string;
        /**
         * Internal path, e.g. /tools/esg-readiness
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Unique page title (handoff p. 227). Falls back to the domain title. " | Enerqa" is appended automatically.
   */
  metaTitle?: string | null;
  /**
   * Unique meta description, roughly 150-160 characters.
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets".
 */
export interface Dataset {
  id: number;
  slug: string;
  title: string;
  /**
   * Brief insights or summary for this dataset.
   */
  description: string;
  file?: (number | null) | Media;
  /**
   * Optional path for API access (e.g. /api/climate/emissions)
   */
  apiEndpoint?: string | null;
  topic?: (number | Category)[] | null;
  date: string;
  /**
   * Organization or entity that produced the dataset.
   */
  provider?: string | null;
  /**
   * Series or dataset identifier.
   */
  identifier?: string | null;
  /**
   * Version or release.
   */
  version?: string | null;
  licence?: string | null;
  licenceUrl?: string | null;
  originalUnit?: string | null;
  /**
   * Geographic scope or level (e.g. Global, Europe, United States).
   */
  geographicLevel?: string | null;
  /**
   * Time period covered by the dataset (e.g. 2010 - 2026).
   */
  observationPeriod?: string | null;
  retrievalTime?: string | null;
  /**
   * Ungated free anonymous download link.
   */
  datasetDownloadUrl?: string | null;
  accessStatus?: ('free' | 'restricted') | null;
  accessCheckedAt?: string | null;
  accessEvidence?: string | null;
  corporateReuse?: boolean | null;
  redistribution?: boolean | null;
  attribution?: string | null;
  /**
   * Iframe URL for interactive charts/maps (Tableau, PowerBI, Observable).
   */
  embedUrl?: string | null;
  /**
   * Ready-to-copy citation format.
   */
  citation?: string | null;
  /**
   * Detailed sources and methodology.
   */
  methodology?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedDatasets?: (number | Dataset)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dashboards".
 */
export interface Dashboard {
  id: number;
  slug: string;
  title: string;
  /**
   * High level overview of the dashboard.
   */
  description: string;
  /**
   * URL of the Tableau, PowerBI, or Observable dashboard to embed.
   */
  embedUrl: string;
  /**
   * Instructions on how to use the dashboard controls/filters.
   */
  controlsInfo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Key takeaways and interpretation of the data.
   */
  interpretation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Internal datasets that power this dashboard.
   */
  underlyingDatasets?: (number | Dataset)[] | null;
  /**
   * Attributions for external data sources not tracked in Datasets.
   */
  externalSources?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-items".
 */
export interface ExternalItem {
  id: number;
  /**
   * Headline or title of the external item
   */
  title: string;
  provider: string;
  source?: string | null;
  date: string;
  /**
   * e.g., Report, News, Press Release
   */
  type: string;
  url: string;
  /**
   * Covered geography (distinct from publisher location)
   */
  geography?: string | null;
  /**
   * Proof of open access or licensing rights
   */
  accessEvidence?: string | null;
  /**
   * Copyright/distribution rights
   */
  rights?: string | null;
  domains?: (number | Domain)[] | null;
  industries?: (number | Industry)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary".
 */
export interface Glossary {
  id: number;
  term: string;
  /**
   * Arabic translation or transliteration of the term.
   */
  termAr?: string | null;
  definition: string;
  /**
   * e.g., Science, Policy, Finance
   */
  category?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category: string;
  /**
   * Optional sort order.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  company?: string | null;
  natureOfEnquiry?: string | null;
  message?: string | null;
  marketingConsent?: boolean | null;
  toolRequested?: (number | null) | Tool;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'tools';
        value: number | Tool;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'domains';
        value: number | Domain;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'datasets';
        value: number | Dataset;
      } | null)
    | ({
        relationTo: 'dashboards';
        value: number | Dashboard;
      } | null)
    | ({
        relationTo: 'external-items';
        value: number | ExternalItem;
      } | null)
    | ({
        relationTo: 'glossary';
        value: number | Glossary;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heading?: T;
  excerpt?: T;
  content?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaKeywords?: T;
  ogImage?: T;
  type?: T;
  author?: T;
  language?: T;
  archiveCategory?: T;
  recordKind?: T;
  dateVerified?: T;
  topic?: T;
  date?: T;
  file?: T;
  bgGradientType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools_select".
 */
export interface ToolsSelect<T extends boolean = true> {
  slug?: T;
  category?: T;
  type?: T;
  title?: T;
  desc?: T;
  image?: T;
  link?: T;
  iframeUrl?: T;
  file?: T;
  industries?: T;
  version?: T;
  access?: T;
  purpose?: T;
  inputs?: T;
  outputs?: T;
  method?: T;
  privacy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains_select".
 */
export interface DomainsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  heroNarrative?: T;
  ctaText?: T;
  capabilities?:
    | T
    | {
        heading?: T;
        slug?: T;
        narrative?: T;
        id?: T;
      };
  relevantIndustries?: T;
  policyUpdates?:
    | T
    | {
        heading?: T;
        narrative?: T;
        sourceNote?: T;
      };
  relevantTools?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  heroNarrative?: T;
  ctaText?: T;
  lifecycleNarrative?: T;
  workAreas?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  relevantTools?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  dataSources?:
    | T
    | {
        provider?: T;
        note?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  metaKeywords?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets_select".
 */
export interface DatasetsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  file?: T;
  apiEndpoint?: T;
  topic?: T;
  date?: T;
  provider?: T;
  identifier?: T;
  version?: T;
  licence?: T;
  licenceUrl?: T;
  originalUnit?: T;
  geographicLevel?: T;
  observationPeriod?: T;
  retrievalTime?: T;
  datasetDownloadUrl?: T;
  accessStatus?: T;
  accessCheckedAt?: T;
  accessEvidence?: T;
  corporateReuse?: T;
  redistribution?: T;
  attribution?: T;
  embedUrl?: T;
  citation?: T;
  methodology?: T;
  relatedDatasets?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dashboards_select".
 */
export interface DashboardsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  embedUrl?: T;
  controlsInfo?: T;
  interpretation?: T;
  underlyingDatasets?: T;
  externalSources?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "external-items_select".
 */
export interface ExternalItemsSelect<T extends boolean = true> {
  title?: T;
  provider?: T;
  source?: T;
  date?: T;
  type?: T;
  url?: T;
  geography?: T;
  accessEvidence?: T;
  rights?: T;
  domains?: T;
  industries?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "glossary_select".
 */
export interface GlossarySelect<T extends boolean = true> {
  term?: T;
  termAr?: T;
  definition?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  company?: T;
  natureOfEnquiry?: T;
  message?: T;
  marketingConsent?: T;
  toolRequested?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-hub-config".
 */
export interface KnowledgeHubConfig {
  id: number;
  heroTitle: string;
  heroTitleAr: string;
  publicationsEyebrow: string;
  publicationsEyebrowAr: string;
  learningMaterialsEyebrow: string;
  learningMaterialsEyebrowAr: string;
  glossaryEyebrow: string;
  glossaryEyebrowAr: string;
  glossaryTitle: string;
  glossaryTitleAr?: string | null;
  glossaryDescription: string;
  glossaryDescriptionAr?: string | null;
  faqsEyebrow: string;
  faqsEyebrowAr: string;
  faqsTitle: string;
  faqsTitleAr?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-portal-sources-config".
 */
export interface DataPortalSourcesConfig {
  id: number;
  /**
   * Introductory text for the Data Portal Sources and Methodology page.
   */
  s01_intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Directory of primary data sources.
   */
  s02_directory?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Policies on attribution and data reuse.
   */
  s03_attribution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Definitions, statistical limits, or context on data smoothing.
   */
  s04_understanding?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-hub-config_select".
 */
export interface KnowledgeHubConfigSelect<T extends boolean = true> {
  heroTitle?: T;
  heroTitleAr?: T;
  publicationsEyebrow?: T;
  publicationsEyebrowAr?: T;
  learningMaterialsEyebrow?: T;
  learningMaterialsEyebrowAr?: T;
  glossaryEyebrow?: T;
  glossaryEyebrowAr?: T;
  glossaryTitle?: T;
  glossaryTitleAr?: T;
  glossaryDescription?: T;
  glossaryDescriptionAr?: T;
  faqsEyebrow?: T;
  faqsEyebrowAr?: T;
  faqsTitle?: T;
  faqsTitleAr?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-portal-sources-config_select".
 */
export interface DataPortalSourcesConfigSelect<T extends boolean = true> {
  s01_intro?: T;
  s02_directory?: T;
  s03_attribution?: T;
  s04_understanding?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}